# Generated by Django 4.2.3 on 2023-07-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to='doctor.doctor', verbose_name='Doctor Name'),
        ),
    ]
