# Generated by Django 4.2.3 on 2023-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.CharField(max_length=100),
        ),
    ]
