# Generated by Django 4.2.3 on 2023-07-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_doc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_start_year', models.DateField(blank=True, null=True)),
                ('degree_end_year', models.DateField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
